
################################################################################
# Task UI OData Calls
################################################################################

@requestId = d3340187-0be9-4f32-ab21-02b667326500

### Metadata
GET http://localhost:4004/odata/v4/asset-disposal-task-ui/$metadata

### Read Requests
GET http://localhost:4004/odata/v4/asset-disposal-task-ui/RequestDetails

### Call Single Request

GET http://localhost:4004/odata/v4/asset-disposal-task-ui/RequestDetails(ID={{requestId}})

### Call Audit Trail Action
POST http://localhost:4004/odata/v4/asset-disposal-task-ui/RequestDetails(ID={{requestId}})/AssetDisposalTaskUI.addAuditTrial
Content-Type: application/json
Accept: application/json

{
  "requestId"  : "1",
  "taskID"     : "2",
  "taskName"   : "3",
  "taskTitle"  : "4",
  "workflowId" : "5"
}

### Call AudiTrail Data
GET http://localhost:4004/odata/v4/asset-disposal-task-ui/RequestDetails(ID={{requestId}})/AuditTrail


### Call Void
POST http://localhost:4004/odata/v4/asset-disposal-task-ui/RequestDetails(ID={{requestId}})/AssetDisposalTaskUI.void