### Variables
@clientid = sb-fb39a0e7-2e75-48d4-8064-d02092d2ed2f!b132941|sdm-di-SDM_DI_PROD-prod!b41064
@clientsecret = xXthyaLDPizdIkujg0SFDjCcStw=


### Step 1 Get OAuth Token
# @name postLogin
POST https://sap-process-automation-tfe.authentication.eu10.hana.ondemand.com/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{clientid}}&client_secret={{clientsecret}}

### Read oauth response
@oauth_token = {{postLogin.response.body.access_token}}

### Create the repository
POST https://api-sdm-di.cfapps.eu10.hana.ondemand.com/rest/v2/repositories
Authorization: Bearer {{oauth_token}}
Content-Type: application/json

{
    "repository": {
        "displayName": "SPPL_REPO_MP1",
        "description": "Test MP",
        "repositoryType": "internal",
        "isVersionEnabled":"false"
    }
}

### All repo browser
GET https://api-sdm-di.cfapps.eu10.hana.ondemand.com/browser
Authorization: Bearer {{oauth_token}}

### Single Repo Browser
@repo = 3d765260-6a8b-46a5-a297-b361aac9136e
DELETE https://api-sdm-di.cfapps.eu10.hana.ondemand.com/browser/{{repo}}?cmisselector=repositoryInfo
Authorization: Bearer {{oauth_token}}
